name: Build and Deploy

## disabled on push for now till able to whitelist GHAs
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, ctype, fileinfo, openssl, tokenizer, pdo, curl, zip, json

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Add global composer bin to PATH
        run: echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Deployer
        run: composer global require deployer/deployer

      - name: Install sshpass & envsubst
        run: sudo apt-get update && sudo apt-get install -y sshpass gettext-base rsync

      - name: Set up SSH for Jumpbox
        run: |
          # Create SSH directory if it doesn't exist
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write the jumpbox private key
          echo "${{ secrets.JUMPBOX_PRIVATE_KEY }}" > ~/.ssh/jumpbox_id_rsa
          chmod 600 ~/.ssh/jumpbox_id_rsa

          # Write the SSH config
          cat > ~/.ssh/config <<EOL
          Host jumpbox
          HostName ${{ secrets.JUMPBOX_HOST }}
          User ${{ secrets.JUMPBOX_USER }}
          IdentityFile ~/.ssh/jumpbox_id_rsa
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null

          Host forger-jump
          HostName ${{ secrets.SSH_HOST }}
          User ${{ secrets.SSH_USER }}
          Port ${{ secrets.SSH_PORT }}
          ProxyJump jumpbox
          PreferredAuthentications password
          PubkeyAuthentication no
          PasswordAuthentication yes
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
          EOL

          # Ensure known_hosts exists to avoid warnings
          touch ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          ./deploy.sh
        env:
          GITHUB_ACTIONS: true
          APP_ENV: production
          APP_NAME: ${{ vars.APP_NAME }}
          APP_URL: ${{ vars.APP_URL }}
          APP_KEY: ${{ secrets.APP_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
          SSHPASS: ${{ secrets.SSHPASS }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_SESSION_PASSWORD: ${{ secrets.REDIS_SESSION_PASSWORD }}
          REDIS_FPC_PASSWORD: ${{ secrets.REDIS_FPC_PASSWORD }}
          OPENSEARCH_USERNAME: ${{ secrets.OPENSEARCH_USERNAME }}
          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_APP_TOKEN }}
